apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "app-js.fullname" . }}
  labels:
    {{- include "app-js.labels" . | nindent 4 }}
    {{- include "library-chart.labels" . | indent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  podmanagementpolicy: {{ .Values.podManagementPolicy }}
  selector:
    matchLabels:
      {{- include "app-js.selectorLabels" . | nindent 6 }}
      {{- include "library-chart.labels" . | indent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "app-js.labels" . | nindent 8 }}
        {{- include "library-chart.labels" . | indent 8 }}
	{{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "app-js.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 3000
          readinessProbe:
            httpGet:
              path: /
              port: 3000
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            {{- include "app-js.envVars" . | nindent 12 }}
          volumeMounts:
            {{- toYaml .Values.volumeMounts | nindent 12}}
      volumes:
      {{ - with .Values.volumes}}
        {{- toYaml . | nindent 8}}
      {{- end}}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  volumeclaimtemplates:  
  {{- toYaml .Values.volumeClaimTemplates | nindent 2}}
